# Site
name: "Datron"
title: "Blog"
description: "Hi this is my blog. I write about technology, finance and startups, sometimes food."
logo: 'assets/images/logo_small.png'
favicon: 'assets/images/logo_small.png'
baseurl: 
include: ["_pages"]
permalink: /:title/
email: datron08012018@gmail.com

# Authors
authors:
  Datron:
    name: Datron
    display_name: Datron
    gravatar: 
    email: datron08012018@gmail.com
    web: https://datron.github.io/
    twitter: https://twitter.com/kartik543214
    description: "I like to build cool stuff, mostly software. Inventor and Dosa enthusiast."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
